### ISSUE TITLE
input directory needs to be defined and input files needs to be transfered to solve this issue

### ISSUE THREAD

**Issue by bala-ruokavirasto** [yetulaxman/InnuendoCliCpouta#1]
(base) ubuntu@innuendo2-master-machine:/mnt/innuendo2_testing/demo_environment/bala$ nohup bash launch_pipeline_selectedsample.sh input_samples_ecoli.txt > test_ecoli &
[1] 719762
(base) ubuntu@innuendo2-master-machine:/mnt/innuendo2_testing/demo_environment/bala$ nohup: ignoring input and redirecting stderr to stdout

(base) ubuntu@innuendo2-master-machine:/mnt/innuendo2_testing/demo_environment/bala$ nano test_ecoli
[1]+  Exit 126                nohup bash launch_pipeline_selectedsample.sh input_samples_ecoli.txt > test_ecoli
(base) ubuntu@innuendo2-master-machine:/mnt/innuendo2_testing/demo_environment/bala$ cat test_ecoli
pipelines, users, input_files
incoming data: /mnt/innuendo2_testing/rawdata/users/incoming/input_files
skipping header
ecoli, cloud-userbala, FIXT-316_S7_L001_1.fastq.gz
incoming data: /mnt/innuendo2_testing/rawdata/cloud-userbala/incoming/FIXT-316_S7_L001_1.fastq.gz
No recognised input files found in the folder:/mnt/innuendo2_testing/rawdata/cloud-userbala/incoming
ecoli, cloud-userbala, FIXT-316_S7_L001_2.fastq.gz
incoming data: /mnt/innuendo2_testing/rawdata/cloud-userbala/incoming/FIXT-316_S7_L001_2.fastq.gz
No recognised input files found in the folder:/mnt/innuendo2_testing/rawdata/cloud-userbala/incoming
ecoli, cloud-userbala, FIAR-847_S5_L001_1.fastq.gz
incoming data: /mnt/innuendo2_testing/rawdata/cloud-userbala/incoming/FIAR-847_S5_L001_1.fastq.gz
No recognised input files found in the folder:/mnt/innuendo2_testing/rawdata/cloud-userbala/incoming
ecoli, cloud-userbala, FIAR-847_S5_L001_2.fastq.gz
incoming data: /mnt/innuendo2_testing/rawdata/cloud-userbala/incoming/FIAR-847_S5_L001_2.fastq.gz
No recognised input files found in the folder:/mnt/innuendo2_testing/rawdata/cloud-userbala/incoming
unique pipeline mentioned
No recognised input files found
Data folder is lcoated here:
launch_pipeline_selectedsample.sh: line 82: cd: /mnt/innuendo2_testing/jobs/cloud-userbala/ecoli_123: No such file or directory
building pipeline in directory:/mnt/innuendo2_testing/jobs/cloud-userbala/ecoli_123
ecoli
========= F L O W C R A F T =========
Build mode
version: 1.4.1
build: 02032019
=====================================
Checking pipeline for errors...
Resulting pipeline string:

 integrity_coverage={'pid':'3','cpus':'2','memory':'\'2GB\''} fastqc_trimmomatic={'pid':'4','cpus':'3','memory':'\'3GB\''} ( reads_kraken2={'pid':'14','cpus':'6','memory':'\'3GB\''} true_coverage={'pid':'5','cpus':'2','memory':'\'2GB\''} ( fastqc={'pid':'6','cpus':'3','memory':'\'3GB\''} check_coverage={'pid':'7','cpus':'2','memory':'\'2GB\''} spades={'pid':'8','scratch':'true','cpus':'6','memory':'\'8GB\''} process_spades={'pid':'9','cpus':'3','memory':'\'3GB\''} assembly_mapping={'pid':'10','cpus':'3','memory':'\'3GB\''} pilon={'pid':'11','cpus':'3','memory':'\'3GB\''} ( mlst={'pid':'12','version':'2.19.0','cpus':'3','memory':'\'3GB\''} chewbbaca={'pid':'13','queue':'\'chewBBACA\'','cpus':'8','memory':'\'8GB\''} | assembly_resfinder={'pid':'29','cpus':'3','memory':'\'3GB\''} | assembly_kraken2={'pid':'24','cpus':'3','memory':'\'3GB\''} | assembly_virulencefinder={'pid':'30','cpus':'3','memory':'\'3GB\''} | insertsize_innu={'pid':'31','cpus':'3','memory':'\'3GB\''} | quast={'pid':'41','version':'5.0.2','cpus':'4','memory':'\'5GB\''} | busco={'pid':'42','version':'5.3.1','cpus':'3','memory':'\'3GB\''} ) | patho_typing={'pid':'18','cpus':'3','memory':'\'3GB\''} | stx_seqtyping={'pid':'19','cpus':'3','memory':'\'3GB\''} | reads_resfinder={'pid':'27','cpus':'3','memory':'\'3GB\''} | reads_virulencefinder={'pid':'25','cpus':'3','memory':'\'3GB\''} | reads_serotypefinder={'pid':'26','cpus':'3','memory':'\'3GB\''} ) | confindr={'pid':'40','version':'0.7.2','cpus':'3','memory':'\'3GB\''} )

Building your awesome pipeline...
        Successfully connected 24 process(es) with 3 fork(s) across 16 lane(s)
        Channels set for init
        Channels set for integrity_coverage
        Channels set for fastqc_trimmomatic
        Channels set for reads_kraken2
        Channels set for confindr
        Channels set for true_coverage
        Channels set for fastqc
        Channels set for patho_typing
        Channels set for stx_seqtyping
        Channels set for reads_resfinder
        Channels set for reads_virulencefinder
        Channels set for reads_serotypefinder
        Channels set for check_coverage
        Channels set for spades
        Channels set for process_spades
        Channels set for assembly_mapping
        Channels set for pilon
        Channels set for mlst
        Channels set for assembly_resfinder
        Channels set for assembly_kraken2
        Channels set for assembly_virulencefinder
        Channels set for insertsize_innu
        Channels set for quast
        Channels set for busco
        Channels set for chewbbaca
        Successfully set 4 secondary channel(s)
        Finished configurations
        Pipeline written into pipeline_ecoli.nf
DONE!
Running ecoli pipeline
Nextflow pipeline is running
lsof: status error on /mnt/innuendo2_testing/jobs/cloud-userbala/ecoli_123/.nextflow/cache/*/db/LOCK: No such file or directory
lsof 4.93.2
 latest revision: https://github.com/lsof-org/lsof
 latest FAQ: https://github.com/lsof-org/lsof/blob/master/00FAQ
 latest (non-formatted) man page: https://github.com/lsof-org/lsof/blob/master/Lsof.8
 usage: [-?abhKlnNoOPRtUvVX] [+|-c c] [+|-d s] [+D D] [+|-E] [+|-e s] [+|-f[gG]]
 [-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+m [m]] [+|-M] [-o [o]] [-p s]
 [+|-r [t]] [-s [p:s]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]
Use the ``-h'' option to get more help information.
process finished
mkdir: cannot create directory ‘results/md5_sha256’: No such file or directory
launch_pipeline_selectedsample.sh: line 136: /mnt/innuendo2_testing/jobs/cloud-userbala/ecoli_123/results/md5_sha256/sha256sum.txt: No such file or directory
launch_pipeline_selectedsample.sh: line 137: /mnt/innuendo2_testing/jobs/cloud-userbala/ecoli_123/results/md5_sha256/md5sum.txt: No such file or directory
Traceback (most recent call last):
  File "combined_reports_short.py", line 22, in <module>
    with open(file_found, 'rt') as reader:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/innuendo2_testing/demo_environment/bala/reports/coverage_3/estimated_coverage_initial.csv'
Traceback (most recent call last):
  File "amr_reports.py", line 23, in <module>
    with open(file_found, 'rt') as reader:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/innuendo2_testing/demo_environment/bala/reports/coverage_3/estimated_coverage_initial.csv'
Traceback (most recent call last):
  File "logs_reports.py", line 65, in <module>
    with open(file_found, 'rt') as reader:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/innuendo2_testing/demo_environment/bala/reports/coverage_3/estimated_coverage_initial.csv'
Traceback (most recent call last):
  File "samples.py", line 22, in <module>
    status_file = pd.read_csv('./reports/status/master_status.csv',names=["samples","process","status"])
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './reports/status/master_status.csv'
Traceback (most recent call last):
  File "typing_reports.py", line 59, in <module>
    with open(file_found, 'rt') as reader:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/innuendo2_testing/demo_environment/bala/reports/coverage_3/estimated_coverage_initial.csv'
launch_pipeline_selectedsample.sh: line 141: /home/ubuntu: Is a directory

**Comment by bala-ruokavirasto** [comment]
Soultion below: (for user "cloud-userbala"- Please rename your own username instead of this)

(base) ubuntu@innuendo2-master-machine:/mnt/innuendo2_testing/demo_environment/bala$ mkdir /mnt/innuendo2_testing/rawdata/cloud-userbala/
(base) ubuntu@innuendo2-master-machine:/mnt/innuendo2_testing/demo_environment/bala$ mkdir /mnt/innuendo2_testing/rawdata/cloud-userbala/incoming
(base) ubuntu@innuendo2-master-machine:/mnt/innuendo2_testing/demo_environment/bala$ cp /mnt/innuendo2_testing/rawdata/cloud-user/incoming/* /mnt/innuendo2_testing/rawdata/cloud-userbala/incoming/.
(base) ubuntu@innuendo2-master-machine:/mnt/innuendo2_testing/demo_environment/bala$ nohup bash launch_pipeline_selectedsample.sh input_samples_ecoli.txt > test_ecoli &
[1] 720098
(base) ubuntu@innuendo2-master-machine:/mnt/innuendo2_testing/demo_environment/bala$ nohup: ignoring input and redirecting stderr to stdout

(base) ubuntu@innuendo2-master-machine:/mnt/innuendo2_testing/demo_environment/bala$ cat test_ecoli
pipelines, users, input_files
incoming data: /mnt/innuendo2_testing/rawdata/users/incoming/input_files
skipping header
ecoli, cloud-userbala, FIXT-316_S7_L001_1.fastq.gz
incoming data: /mnt/innuendo2_testing/rawdata/cloud-userbala/incoming/FIXT-316_S7_L001_1.fastq.gz
in raw file : /mnt/innuendo2_testing/rawdata/cloud-userbala/incoming
inuput file FIXT-316_S7_L001_1.fastq.gz
raw file : /mnt/innuendo2_testing/rawdata/cloud-userbala/incoming/FIXT-316_S7_L001_1.fastq.gz
target file: /mnt/innuendo2_testing/jobs/cloud-userbala/ecoli_123/data/FIXT-316_S7_L001_1.fastq.gz
ecoli, cloud-userbala, FIXT-316_S7_L001_2.fastq.gz
incoming data: /mnt/innuendo2_testing/rawdata/cloud-userbala/incoming/FIXT-316_S7_L001_2.fastq.gz
in raw file : /mnt/innuendo2_testing/rawdata/cloud-userbala/incoming
inuput file FIXT-316_S7_L001_2.fastq.gz
raw file : /mnt/innuendo2_testing/rawdata/cloud-userbala/incoming/FIXT-316_S7_L001_2.fastq.gz
target file: /mnt/innuendo2_testing/jobs/cloud-userbala/ecoli_123/data/FIXT-316_S7_L001_2.fastq.gz
ecoli, cloud-userbala, FIAR-847_S5_L001_1.fastq.gz
incoming data: /mnt/innuendo2_testing/rawdata/cloud-userbala/incoming/FIAR-847_S5_L001_1.fastq.gz
in raw file : /mnt/innuendo2_testing/rawdata/cloud-userbala/incoming
inuput file FIAR-847_S5_L001_1.fastq.gz
raw file : /mnt/innuendo2_testing/rawdata/cloud-userbala/incoming/FIAR-847_S5_L001_1.fastq.gz
target file: /mnt/innuendo2_testing/jobs/cloud-userbala/ecoli_123/data/FIAR-847_S5_L001_1.fastq.gz
ecoli, cloud-userbala, FIAR-847_S5_L001_2.fastq.gz
incoming data: /mnt/innuendo2_testing/rawdata/cloud-userbala/incoming/FIAR-847_S5_L001_2.fastq.gz
in raw file : /mnt/innuendo2_testing/rawdata/cloud-userbala/incoming
inuput file FIAR-847_S5_L001_2.fastq.gz
raw file : /mnt/innuendo2_testing/rawdata/cloud-userbala/incoming/FIAR-847_S5_L001_2.fastq.gz
target file: /mnt/innuendo2_testing/jobs/cloud-userbala/ecoli_123/data/FIAR-847_S5_L001_2.fastq.gz
unique pipeline mentioned
Fastq file(s) found with pattern *_1.fastq.gz
Data folder is lcoated here: /mnt/innuendo2_testing/jobs/cloud-userbala/ecoli_123/data/*_{1,2}.fastq.gz
building pipeline in directory:/mnt/innuendo2_testing/jobs/cloud-userbala/ecoli_123
ecoli
========= F L O W C R A F T =========
Build mode
version: 1.4.1
build: 02032019
=====================================
Checking pipeline for errors...
Resulting pipeline string:

 integrity_coverage={'pid':'3','cpus':'2','memory':'\'2GB\''} fastqc_trimmomatic={'pid':'4','cpus':'3','memory':'\'3GB\''} ( reads_kraken2={'pid':'14','cpus':'6','memory':'\'3GB\''} true_coverage={'pid':'5','cpus':'2','memory':'\'2GB\''} ( fastqc={'pid':'6','cpus':'3','memory':'\'3GB\''} check_coverage={'pid':'7','cpus':'2','memory':'\'2GB\''} spades={'pid':'8','scratch':'true','cpus':'6','memory':'\'8GB\''} process_spades={'pid':'9','cpus':'3','memory':'\'3GB\''} assembly_mapping={'pid':'10','cpus':'3','memory':'\'3GB\''} pilon={'pid':'11','cpus':'3','memory':'\'3GB\''} ( mlst={'pid':'12','version':'2.19.0','cpus':'3','memory':'\'3GB\''} chewbbaca={'pid':'13','queue':'\'chewBBACA\'','cpus':'8','memory':'\'8GB\''} | assembly_resfinder={'pid':'29','cpus':'3','memory':'\'3GB\''} | assembly_kraken2={'pid':'24','cpus':'3','memory':'\'3GB\''} | assembly_virulencefinder={'pid':'30','cpus':'3','memory':'\'3GB\''} | insertsize_innu={'pid':'31','cpus':'3','memory':'\'3GB\''} | quast={'pid':'41','version':'5.0.2','cpus':'4','memory':'\'5GB\''} | busco={'pid':'42','version':'5.3.1','cpus':'3','memory':'\'3GB\''} ) | patho_typing={'pid':'18','cpus':'3','memory':'\'3GB\''} | stx_seqtyping={'pid':'19','cpus':'3','memory':'\'3GB\''} | reads_resfinder={'pid':'27','cpus':'3','memory':'\'3GB\''} | reads_virulencefinder={'pid':'25','cpus':'3','memory':'\'3GB\''} | reads_serotypefinder={'pid':'26','cpus':'3','memory':'\'3GB\''} ) | confindr={'pid':'40','version':'0.7.2','cpus':'3','memory':'\'3GB\''} )

Building your awesome pipeline...
        Successfully connected 24 process(es) with 3 fork(s) across 16 lane(s)
        Channels set for init
        Channels set for integrity_coverage
        Channels set for fastqc_trimmomatic
        Channels set for reads_kraken2
        Channels set for confindr
        Channels set for true_coverage
        Channels set for fastqc
        Channels set for patho_typing
        Channels set for stx_seqtyping
        Channels set for reads_resfinder
        Channels set for reads_virulencefinder
        Channels set for reads_serotypefinder
        Channels set for check_coverage
        Channels set for spades
        Channels set for process_spades
        Channels set for assembly_mapping
        Channels set for pilon
        Channels set for mlst
        Channels set for assembly_resfinder
        Channels set for assembly_kraken2
        Channels set for assembly_virulencefinder
        Channels set for insertsize_innu
        Channels set for quast
        Channels set for busco
        Channels set for chewbbaca
        Successfully set 4 secondary channel(s)
        Finished configurations
        Pipeline written into pipeline_ecoli.nf
DONE!
Running ecoli pipeline
